Add feature (clean)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -8,6 +8,12 @@ on:
   pull_request:
     branches: [ "main" ]
 
+  # Run every night at midnight UTC
+    schedule:
+      - cron: '0 0 * * *'
+    # Allow developers to manually trigger the workflow from the GitHub Actions tab
+    workflow_dispatch:
+
 jobs:
   test:
     name: Build & Test
@@ -31,10 +37,51 @@ jobs:
     - name: Install the project
       run: uv sync --frozen
 
+
     # Check code formatting and lint
     - name: Check code
       run: uvx ruff check . --output-format=github
 
     # Run tests
     - name: Run tests
-      run: uv run pytest
+      run: uv run pytest """--junitxml=junit.xml"""
+
+    # Show test results in a developer friendly way
+    - name: Create test result summary
+      uses: test-summary/action@v2
+      with:
+        paths: "junit.xml"
+      # ensure this runs even if tests fail
+      if: always()
+
+  scan:
+    name: Security Checks
+    runs-on: ubuntu-latest
+    permissions:
+      pull-requests: write
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Install uv
+        uses: astral-sh/setup-uv@v5
+        with:
+          enable-cache: true
+
+      - name: Set up Python
+        run: uv python install
+
+      - name: Scan for vulnerable dependencies
+        run: | 
+          set -o pipefail
+          echo "### 🛡️ Security Audit Results" >> $GITHUB_STEP_SUMMARY
+          echo '```text' >> $GITHUB_STEP_SUMMARY
+          uvx uv-secure --config=pyproject.toml | tee -a $GITHUB_STEP_SUMMARY
+          echo '```' >> $GITHUB_STEP_SUMMARY
+
+      - name: Scan for secrets
+        uses: gitleaks/gitleaks-action@v2
+        if: always()
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
